<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MesinCelupSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'no_mesin' => 8,
                'min_caps' => 3.6,
                'max_caps' => 3.6,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'MC BENANG SAMPLE',
            ],
            [
                'no_mesin' => 23,
                'min_caps' => 151.2,
                'max_caps' => 151.2,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 24,
                'min_caps' => 216,
                'max_caps' => 216,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 25,
                'min_caps' => 324,
                'max_caps' => 324,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 32,
                'min_caps' => 518.4,
                'max_caps' => 518.4,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 35,
                'min_caps' => 864,
                'max_caps' => 864,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 36,
                'min_caps' => 1029.6,
                'max_caps' => 1209.6,
                'jml_lot' => 1,
                'lmd' => 'LM',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 1,
                'min_caps' => 4.8,
                'max_caps' => 9.6,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'MC BENANG SAMPLE',
            ],
            [
                'no_mesin' => 2,
                'min_caps' => 4.8,
                'max_caps' => 9.6,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'MC BENANG SAMPLE',
            ],
            [
                'no_mesin' => 5,
                'min_caps' => 7.2,
                'max_caps' => 14.4,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'MC BENANG SAMPLE',
            ],
            [
                'no_mesin' => 6,
                'min_caps' => 7.2,
                'max_caps' => 14.4,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'MC BENANG SAMPLE',
            ],
            [
                'no_mesin' => 7,
                'min_caps' => 3.6,
                'max_caps' => 7.2,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'MC BENANG SAMPLE',
            ],
            [
                'no_mesin' => 10,
                'min_caps' => 14.4,
                'max_caps' => 28.8,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 11,
                'min_caps' => 14.4,
                'max_caps' => 28.8,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 12,
                'min_caps' => 36,
                'max_caps' => 72,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 13,
                'min_caps' => 36,
                'max_caps' => 72,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 15,
                'min_caps' => 86.4,
                'max_caps' => 172.8,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 16,
                'min_caps' => 86.4,
                'max_caps' => 172.8,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 22,
                'min_caps' => 151.2,
                'max_caps' => 302.4,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 28,
                'min_caps' => 1324.8,
                'max_caps' => 2649.6,
                'jml_lot' => 2,
                'lmd' => 'WHITE',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 29,
                'min_caps' => 1324.8,
                'max_caps' => 2649.6,
                'jml_lot' => 2,
                'lmd' => 'BLACK',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 31,
                'min_caps' => 1388.4,
                'max_caps' => 2776.8,
                'jml_lot' => 2,
                'lmd' => 'BLACK',
                'ket_mesin' => 'BENANG',
            ],
            [
                'no_mesin' => 35,
                'min_caps' => 864,
                'max_caps' => 864,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'NYLON',
            ],
            [
                'no_mesin' => 34,
                'min_caps' => 864,
                'max_caps' => 864,
                'jml_lot' => 1,
                'lmd' => 'D',
                'ket_mesin' => 'NYLON',
            ],
            [
                'no_mesin' => 21,
                'min_caps' => 151.2,
                'max_caps' => 302.4,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'NYLON',
            ],
            [
                'no_mesin' => 33,
                'min_caps' => 864,
                'max_caps' => 1728,
                'jml_lot' => 2,
                'lmd' => 'LM',
                'ket_mesin' => 'NYLON',
            ],
            [
                'no_mesin' => 3,
                'min_caps' => 336,
                'max_caps' => 672,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'ACRYLIC',
            ],
            [
                'no_mesin' => 4,
                'min_caps' => 352,
                'max_caps' => 704,
                'jml_lot' => 2,
                'lmd' => 'LMD',
                'ket_mesin' => 'ACRYLIC',
            ],
            [
                'no_mesin' => 5,
                'min_caps' => 81,
                'max_caps' => 81,
                'jml_lot' => 1,
                'lmd' => 'LMD',
                'ket_mesin' => 'ACRYLIC',
            ]
        ];

        // Using Query Builder
        $this->db->table('mesin_celup')->insertBatch($data);
    }
}
