<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MesinCovering extends Seeder
{
    public function run()
    {
        $data = [
            // RPR
            [
                'no_mesin' => 1,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 10/2',
                'jml_spindle' => 80,
                'tahun' => '1994',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 2,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '1994',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 3,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '1996',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 4,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '1997',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 5,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '1999',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 6,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '1999',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 7,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '2000',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 8,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '2003',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 9,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'ITALY',
                'merk' => 'RPR',
                'type' => 'GSP 18',
                'jml_spindle' => 216,
                'tahun' => '2004',
                'jml_unit' => 3,
            ],
            // IL SHIN
            [
                'no_mesin' => 10,
                'nama' => 'SINGLE COVERING (ORIGINAL)',
                'jenis' => 'SINGLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'ISC/1000/250/208',
                'jml_spindle' => 208,
                'tahun' => '2005',
                'jml_unit' => 7,
            ],
            [
                'no_mesin' => 11,
                'nama' => 'SINGLE COVERING (ORIGINAL)',
                'jenis' => 'SINGLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'ISC/1000/250/208',
                'jml_spindle' => 208,
                'tahun' => '2006',
                'jml_unit' => 4,
            ],
            [
                'no_mesin' => 12,
                'nama' => 'SINGLE COVERING (ORIGINAL)',
                'jenis' => 'SINGLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'ISC/1000/250/208',
                'jml_spindle' => 208,
                'tahun' => '2007',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 13,
                'nama' => 'SINGLE COVERING (ORIGINAL)',
                'jenis' => 'SINGLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'SC/1000/250/208 sc/dc',
                'jml_spindle' => 208,
                'tahun' => '2006',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 14,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KSC-002',
                'jml_spindle' => 208,
                'tahun' => '2010',
                'jml_unit' => 6,
            ],
            [
                'no_mesin' => 15,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KSC-002',
                'jml_spindle' => 208,
                'tahun' => '2011',
                'jml_unit' => 8,
            ],
            [
                'no_mesin' => 16,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KSC-002',
                'jml_spindle' => 208,
                'tahun' => '2012',
                'jml_unit' => 6,
            ],
            [
                'no_mesin' => 17,
                'nama' => 'SINGLE COVERING',
                'jenis' => 'SINGLE COVERING',
                'buatan' => 'KOREA',
                'merk' => 'KOSUNG',
                'type' => 'KS1000/234',
                'jml_spindle' => 234,
                'tahun' => '2016',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 18,
                'nama' => 'DOUBLE COVERING (ORIGINAL)',
                'jenis' => 'DOUBLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'ISC/1000/250/84',
                'jml_spindle' => 168,
                'tahun' => '2005',
                'jml_unit' => 3,
            ],
            [
                'no_mesin' => 19,
                'nama' => 'DOUBLE COVERING (ORIGINAL)',
                'jenis' => 'DOUBLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'ISC/1000/250/84',
                'jml_spindle' => 168,
                'tahun' => '2006',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 20,
                'nama' => 'DOUBLE COVERING (ORIGINAL)',
                'jenis' => 'DOUBLE COVERING (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'ISC/1000/250/84',
                'jml_spindle' => 168,
                'tahun' => '2007',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 21,
                'nama' => 'DOUBLE COVERING',
                'jenis' => 'DOUBLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KDC-01',
                'jml_spindle' => 168,
                'tahun' => '2008',
                'jml_unit' => 3,
            ],
            [
                'no_mesin' => 22,
                'nama' => 'DOUBLE COVERING',
                'jenis' => 'DOUBLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KDC-01',
                'jml_spindle' => 168,
                'tahun' => '2009',
                'jml_unit' => 4,
            ],
            [
                'no_mesin' => 23,
                'nama' => 'DOUBLE COVERING',
                'jenis' => 'DOUBLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KDC-01',
                'jml_spindle' => 168,
                'tahun' => '2010',
                'jml_unit' => 6,
            ],
            [
                'no_mesin' => 24,
                'nama' => 'DOUBLE COVERING',
                'jenis' => 'DOUBLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KDC-01',
                'jml_spindle' => 168,
                'tahun' => '2011',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 25,
                'nama' => 'DOUBLE COVERING',
                'jenis' => 'DOUBLE COVERING',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KDC-01',
                'jml_spindle' => 168,
                'tahun' => '2012',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 26,
                'nama' => 'DOUBLE COVERING',
                'jenis' => 'DOUBLE COVERING',
                'buatan' => 'KOREA',
                'merk' => 'KOSUNG',
                'type' => 'KS1000/1000',
                'jml_spindle' => 168,
                'tahun' => '2017',
                'jml_unit' => 1,
            ],
            // DCY IL SHIN
            [
                'no_mesin' => 27,
                'nama' => 'AIR JET COVERING',
                'jenis' => 'AIR JET COVERING',
                'buatan' => 'ITALY',
                'merk' => 'FADIS',
                'type' => 'U-0066DX',
                'jml_spindle' => 48,
                'tahun' => '2012',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 28,
                'nama' => 'AIR JET COVERING',
                'jenis' => 'AIR JET COVERING',
                'buatan' => 'JAPAN',
                'merk' => 'AIKI',
                'type' => 'AT-501RWSI-B',
                'jml_spindle' => 108,
                'tahun' => '2013',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 29,
                'nama' => 'AIR JET COVERING',
                'jenis' => 'AIR JET COVERING',
                'buatan' => 'ITALY',
                'merk' => 'FADIS',
                'type' => 'UN-000101',
                'jml_spindle' => 48,
                'tahun' => '2014',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 30,
                'nama' => 'AIR JET COVERING',
                'jenis' => 'AIR JET COVERING',
                'buatan' => 'ITALY',
                'merk' => 'FADIS',
                'type' => 'UN-000133',
                'jml_spindle' => 48,
                'tahun' => '2016',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 31,
                'nama' => 'AIR JET COVERING',
                'jenis' => 'AIR JET COVERING',
                'buatan' => 'ITALY',
                'merk' => 'FADIS',
                'type' => 'UN-000162',
                'jml_spindle' => 48,
                'tahun' => '2018',
                'jml_unit' => 1,
            ],
            // MESIN BOBIN WINDER IL SHIN
            [
                'no_mesin' => 32,
                'nama' => 'BOBBIN WINDER MC IL SHIN (ORIGINAL)',
                'jenis' => 'BOBBIN WINDER MC IL SHIN (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'IL SHIN',
                'type' => 'STV-110',
                'jml_spindle' => 88,
                'tahun' => '2005',
                'jml_unit' => 3,
            ],
            [
                'no_mesin' => 33,
                'nama' => 'BOBBIN WINDER MC IL SHIN',
                'jenis' => 'BOBBIN WINDER MC IL SHIN',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KW-01',
                'jml_spindle' => 88,
                'tahun' => '2006',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 34,
                'nama' => 'BOBBIN WINDER MC IL SHIN (ORIGINAL)',
                'jenis' => 'BOBBIN WINDER MC IL SHIN (ORIGINAL)',
                'buatan' => 'KOREA',
                'merk' => 'KH TEX',
                'type' => 'STV-110',
                'jml_spindle' => 88,
                'tahun' => '2009',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 35,
                'nama' => 'BOBBIN WINDER MC IL SHIN',
                'jenis' => 'BOBBIN WINDER MC IL SHIN',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KW-01',
                'jml_spindle' => 60,
                'tahun' => '2010',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 36,
                'nama' => 'BOBBIN WINDER MC IL SHIN',
                'jenis' => 'BOBBIN WINDER MC IL SHIN',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KW-01',
                'jml_spindle' => 60,
                'tahun' => '2011',
                'jml_unit' => 4,
            ],
            [
                'no_mesin' => 38,
                'nama' => 'BOBBIN WINDER MC IL SHIN',
                'jenis' => 'BOBBIN WINDER MC IL SHIN',
                'buatan' => 'KHT',
                'merk' => 'IL SHIN',
                'type' => 'KW-01',
                'jml_spindle' => 60,
                'tahun' => '2012',
                'jml_unit' => 1,
            ],
            // MESIN WINDER SPOOLEX
            [
                'no_mesin' => 39,
                'nama' => 'BOBBIN WINDER',
                'jenis' => 'BOBBIN WINDER',
                'buatan' => 'ITALY',
                'merk' => 'FADIS',
                'type' => 'SINCRO SPRINT RW306',
                'jml_spindle' => 16,
                'tahun' => '2003',
                'jml_unit' => 1,
            ],
            // MESIN WINDING SINCRO SPRINT
            [
                'no_mesin' => 40,
                'nama' => 'PRECISION WINDER',
                'jenis' => 'KELOS KARET',
                'buatan' => 'JAPAN',
                'merk' => 'MURATA',
                'type' => '56',
                'jml_spindle' => 12,
                'tahun' => '1971',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 41,
                'nama' => 'PRECISION WINDER',
                'jenis' => 'KELOS KARET',
                'buatan' => 'JAPAN',
                'merk' => 'MURATA',
                'type' => '56',
                'jml_spindle' => 12,
                'tahun' => '1973',
                'jml_unit' => 1,
            ],
            [
                'no_mesin' => 42,
                'nama' => 'PRECISION WINDER',
                'jenis' => 'KELOS KARET',
                'buatan' => 'JAPAN',
                'merk' => 'MURATA',
                'type' => '56',
                'jml_spindle' => 12,
                'tahun' => '1973',
                'jml_unit' => 2,
            ],
            [
                'no_mesin' => 43,
                'nama' => 'PRECISION WINDER',
                'jenis' => 'KELOS KARET',
                'buatan' => 'JAPAN',
                'merk' => 'MURATA',
                'type' => '56',
                'jml_spindle' => 12,
                'tahun' => '1974',
                'jml_unit' => 5,
            ],
        ];

        // Using Query Builder
        $this->db->table('mesin_covering')->insertBatch($data);
    }
}
